### PR TITLE
Hide main from Text.Blaze.Html5

### PR DESCRIPTION
**Pull request by aycanirican**

### CODE REVIEW

**Comment by acw** [comment]
Thanks for the patch!

**Comment by utdemir** [comment]
Hey, can you release a new version with this patch?

**Comment by peti** [comment]
It would be great if you could release a new version to Hackage that contains this fix. Please! :pray:

**Comment by elliottt** [comment]
Uploaded!  Sorry for the delay :)

**Comment by aycanirican** [comment]
@elliottt I couldn't see a new version in hackage. Did you forget to upload?

**Comment by elliottt** [comment]
Should be available as 2.6.0.0 now. Sorry about that!

**Pull request merged**
